# Generated by Django 4.2 on 2023-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mrp', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField(verbose_name='quantity')),
                ('image', models.URLField()),
                ('in_stocks', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('types', models.CharField(choices=[('clothing', 'clothing'), ('sports', 'sports'), ('electronics', 'electronics'), ('books', 'books'), ('homedecor', 'homedecor')], max_length=20)),
                ('brand', models.CharField(max_length=200)),
            ],
        ),
    ]
